#! /bin/sh

# /********** ---> Sxhkd exec <--- **********\
pgrep -x sxhkd > /dev/null || sxhkd &

# /********** ---> Auto start <--- **********\
dunst &
xsetroot -cursor_name left_ptr &
libinput-gestures-setup start &
feh --bg-fill ~/.config/backgrounds/bg-03.jpg &
exec xfce4-power-manager &
exec xfce4-screensaver &
sh ~/.config/polybar/bar_launch.sh &
picom -b &

# /********** ---> Bspwm config <--- **********\
bspc monitor -d I II III IV V VI
#bspc monitor HDMI-0 -d VII VIII XI

bspc config border_width         5
bspc config window_gap          25
#bspc config border_radius       15
bspc config top_padding         35
bspc config bottom_padding      15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#191724"
bspc config normal_border_color "#191724"
